version: '3.8'

services:

    gitlab:
        image: 'gitlab/gitlab-ee:latest'
        container_name: gitlab.local
        restart: 'no'
        volumes:
            - './docker/applications/gitlab/config:/etc/gitlab'
            - './docker/applications/gitlab/logs:/var/log/gitlab'
            - './docker/applications/gitlab/data:/var/opt/gitlab'
        ports:
            - '80:80'
            - '443:443'
            - '23:22'
        environment:
          GITLAB_OMNIBUS_CONFIG: |
            external_url 'https://gitlab.local'
            letsencrypt['enable'] = false
            # Add any other gitlab.rb configuration here, each on its own line
    
    gitlab-runner:
        build:
            context: ./docker/images/gitlab-runner
            dockerfile: Dockerfile
        image: gitlab/gitlab-runner:alpine
        container_name: gitlab-runner
        restart: always
        volumes: 
            - './docker/applications/gitlab-runner/config/:/etc/gitlab-runner/'
            - '/var/run/docker.sock:/var/run/docker.sock'
        depends_on: 
            - gitlab 



                    